import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const [thumbnailUrl, setThumbnailUrl] = useState("");

  useEffect(() => {
    // Set up the API request
    const apiKey = "AIzaSyB5xYt8UAoxkcYPYf43NABvWqFbIMMmfbs";
    const query = "cat";
    const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&key=${apiKey}`;

    // Send the request
    fetch(url)
      .then((response) => response.json())
      .then((responseJson) => {
        // Get the list of videos from the response
        const videos = responseJson.items;

        // Select a random video from the list
        const randomIndex = Math.floor(Math.random() * videos.length);
        const randomVideo = videos[randomIndex];

        // Get the thumbnail URL of the random video
        const thumbnailUrl = randomVideo.snippet.thumbnails.default.url;

        setThumbnailUrl(thumbnailUrl);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image width={400} height={250} src={thumbnailUrl} alt="Random thumbnail" />
    </>
  );
}
